export const serviceDepth = {
  en: {
    homeTitle: "What the system actually changes.",
    homeIntro: "A page, an automation or a tool only matters when it fixes a real handoff. Find the situation that sounds familiar.",
    flowTitle: "A lead should not wait for the next working day.",
    flowIntro: "Here are practical flows we can build around the tools you already use. Some steps are simple rules; AI belongs only where information needs interpretation.",
    flowLabel: "Select a workflow",
    flowNote: "The exact steps depend on your tools, consent requirements and how your team works.",
    labels: { problem: "Where it breaks", build: "What we build", after: "What changes", components: "Typical components", fit: "Good fit", scope: "Potential scope", impact: "Business effect", workflow: "Example workflow", explore: "Explore the scope", discuss: "Show us this bottleneck" },
    heroTitle: "We build the missing system between attention and execution.",
    heroLead: "Start with the commercial or operational failure. Then choose the smallest useful combination of experience, automation, integration and software.",
    items: [
      {
        id: "conversion-systems", title: "Conversion systems", statement: "Traffic is expensive. Losing the customer after the click is more expensive.",
        problem: "A paid lead lands on an outdated page, cannot understand the offer on mobile, or gives up before a long form and confusing booking path.",
        build: "We connect the offer, proof, action and lead handoff so a visitor can move from interest to a useful inquiry or booking.",
        after: "The next action is clear, the lead arrives with context, and tracking shows where people leave the journey.",
        components: ["Landing and campaign pages", "Commercial websites", "Offer and CTA structure", "Mobile conversion UX", "Forms and qualification", "Booking and CRM handoff", "Analytics and performance"],
        fit: "Useful when you already pay for traffic, receive inquiries that lack context, or have a booking path that makes customers work too hard.",
        scope: "A focused landing sprint can start around $4,000. A broader commercial website may be around $8,500; integrations and depth determine the final scope.",
        impact: ["More revenue opportunity", "Better visibility"],
        workflow: ["Traffic", "Clear offer", "Trust", "Action", "Qualified lead", "Handoff"],
      },
      {
        id: "business-automation", title: "AI and business automation", statement: "A request arrives at 22:14. The response and handoff should not depend on someone checking an inbox tomorrow.",
        problem: "Leads wait for replies, missed calls disappear, appointments need manual reminders, and staff copy the same details between an inbox, spreadsheet and CRM.",
        build: "We automate the repetitive layer around your team: response, routing, follow-up and data movement. AI is used when a request or document genuinely needs interpretation.",
        after: "The right person gets the right context sooner, routine steps happen reliably, and your team keeps control of decisions that need judgment.",
        components: ["Instant lead response", "Missed-call text-back", "Email and SMS follow-up", "Qualification and lead routing", "Booking and reminders", "CRM pipeline workflows", "Document extraction", "Internal alerts and reporting"],
        fit: "Useful when response time varies, a sales team repeats the same follow-ups, or administrative work delays service delivery.",
        scope: "One focused workflow can be implemented first. More channels, exceptions and integrations expand the implementation scope.",
        impact: ["Less manual work", "Faster operations"],
        workflow: ["Inquiry", "Immediate reply", "Qualification", "CRM update", "Owner notified", "Follow-up"],
      },
      {
        id: "custom-tools", title: "Custom tools and integrations", statement: "Sometimes you need your existing software to work together, not another subscription.",
        problem: "A spreadsheet has become an internal application. Staff repeat calculations, systems cannot exchange data, and managers cannot see one reliable operational view.",
        build: "We make the missing software layer: a focused tool, portal, calculator, dashboard or integration built around the actual workflow.",
        after: "Information moves once, the process is easier to operate, and the people responsible can see its current state.",
        components: ["Staff and client portals", "Dashboards and admin tools", "Quote and estimate calculators", "API and CRM integrations", "Calendar and payment handoffs", "Data synchronization", "Narrow workflow apps and MVPs"],
        fit: "Useful when off-the-shelf software almost works, a spreadsheet runs a critical process, or several apps require repeated copy-paste.",
        scope: "A narrow integration can be scoped separately. Larger custom systems often exceed $10,000 when backend, permissions or data migration are involved.",
        impact: ["Less manual work", "Better visibility"],
        workflow: ["Request", "Shared data", "Business rule", "Staff tool", "Status visible"],
      },
      {
        id: "diagnostic", title: "Diagnostic / system design", statement: "If the problem is clear but the build is not, define the intervention before buying it.",
        problem: "Leads disappear, a workflow wastes time, or the tools are disconnected—but nobody can say whether the answer is a better page, automation, integration or software.",
        build: "We map the bottleneck, its business importance, the current stack and the smallest intervention worth building. We also identify what should stay as it is.",
        after: "You have a buildable scope, dependencies, acceptance criteria and a measurement plan—not an endless strategy document.",
        components: ["Bottleneck and handoff map", "Commercial and operational stakes", "Current-tool review", "Proposed intervention", "Integration requirements", "Implementation scope", "Measurement after launch"],
        fit: "Useful when you know something is leaking money or time but cannot yet define the right system or safe starting point.",
        scope: "A focused diagnostic ends with a scoped recommendation. If implementation follows, the build is priced separately against agreed requirements.",
        impact: ["Better visibility", "Faster operations"],
        workflow: ["Current process", "Constraint", "Options", "Buildable scope", "Measure"],
      },
    ],
    examples: [
      { title: "New lead", steps: ["Lead arrives", "Immediate reply", "Qualification", "Booking option", "CRM entry", "Owner notified", "Follow-up"], note: "Rules handle timing and routing. AI may summarize an unstructured request if useful." },
      { title: "Missed call", steps: ["Call missed", "SMS sent", "Customer replies", "Request categorized", "Staff notified"], note: "A simple deterministic flow can handle most of this without AI." },
      { title: "Website inquiry", steps: ["Form received", "Context extracted", "Team selected", "CRM updated", "Next action scheduled"], note: "AI can extract context from free text; routing and follow-up remain explicit rules." },
      { title: "Appointment", steps: ["Booking", "Confirmation", "Reminder", "Attendance check", "Post-visit follow-up"], note: "A reliable calendar and message workflow often needs no AI at all." },
    ],
  },
  ua: {
    homeTitle: "Що насправді змінює система.",
    homeIntro: "Сторінка, автоматизація чи інструмент мають сенс лише тоді, коли усувають конкретний розрив у процесі. Знайдіть знайому ситуацію.",
    flowTitle: "Заявка не повинна чекати наступного робочого дня.",
    flowIntro: "Ці процеси можна побудувати навколо ваших наявних інструментів. Частині кроків достатньо простих правил; ШІ потрібен там, де треба розуміти зміст інформації.",
    flowLabel: "Оберіть процес", flowNote: "Точні кроки залежать від ваших інструментів, правил згоди та роботи команди.",
    labels: { problem: "Де виникає збій", build: "Що створюємо", after: "Що змінюється", components: "Типові складові", fit: "Коли це доречно", scope: "Можливий обсяг", impact: "Вплив на бізнес", workflow: "Приклад процесу", explore: "Детальніше про послугу", discuss: "Опишіть це вузьке місце" },
    heroTitle: "Будуємо відсутню систему між увагою клієнта та виконанням.",
    heroLead: "Починаємо з комерційного чи операційного збою. Потім добираємо найменше корисне поєднання інтерфейсу, автоматизації, інтеграцій і ПЗ.",
    items: [
      { id: "conversion-systems", title: "Конверсійні системи", statement: "Трафік коштує дорого. Втрачати клієнта після кліку — ще дорожче.", problem: "Людина переходить із реклами на застарілу сторінку, не розуміє пропозиції з телефона або полишає довгу форму й заплутаний запис.", build: "Поєднуємо пропозицію, довіру, дію та передачу заявки, щоб шлях від інтересу до звернення був зрозумілим.", after: "Наступна дія очевидна, заявка містить потрібний контекст, а аналітика показує, де люди полишають шлях.", components: ["Лендинги й сторінки кампаній", "Комерційні сайти", "Структура пропозиції та CTA", "Мобільний UX", "Форми й кваліфікація", "Запис і передача в CRM", "Аналітика та швидкодія"], fit: "Коли ви вже платите за трафік, отримуєте неповні заявки або втрачаєте людей у складному записі.", scope: "Сфокусований лендинг може починатися від $4,000, ширший сайт — близько $8,500. Остаточний обсяг залежить від інтеграцій і глибини роботи.", impact: ["Більше можливостей для продажу", "Краща видимість"], workflow: ["Трафік", "Чітка пропозиція", "Довіра", "Дія", "Якісна заявка", "Передача"] },
      { id: "business-automation", title: "ШІ та бізнес-автоматизація", statement: "Заявка надійшла о 22:14. Відповідь і передача не мають залежати від перевірки пошти завтра.", problem: "Клієнти чекають відповіді, пропущені дзвінки губляться, нагадування надсилають вручну, а дані копіюють між поштою, таблицею та CRM.", build: "Автоматизуємо повторювані дії навколо команди: відповідь, маршрутизацію, нагадування й рух даних. ШІ застосовуємо там, де потрібно зрозуміти запит чи документ.", after: "Потрібна людина швидше отримує контекст, рутинні кроки виконуються стабільно, а рішення, що потребують оцінки, лишаються за командою.", components: ["Швидка відповідь на заявку", "SMS після пропущеного дзвінка", "Email і SMS-супровід", "Кваліфікація та маршрутизація", "Запис і нагадування", "CRM-процеси", "Витяг даних із документів", "Сповіщення та звіти"], fit: "Коли швидкість відповіді нестала, продажі повторюють ті самі дії або адміністративна робота затримує послугу.", scope: "Можна почати з одного процесу. Додаткові канали, винятки та інтеграції розширюють обсяг реалізації.", impact: ["Менше ручної роботи", "Швидші операції"], workflow: ["Заявка", "Відповідь", "Кваліфікація", "Оновлення CRM", "Сповіщення", "Супровід"] },
      { id: "custom-tools", title: "Власні інструменти та інтеграції", statement: "Іноді вам не потрібна нова підписка. Потрібно, щоб наявне ПЗ працювало разом.", problem: "Таблиця стала внутрішньою програмою. Працівники повторюють розрахунки, системи не обмінюються даними, а керівник не бачить єдиної картини.", build: "Створюємо відсутній програмний шар: конкретний інструмент, портал, калькулятор, панель даних чи інтеграцію під реальний процес.", after: "Дані вводяться один раз, процесом легше керувати, а відповідальні бачать його поточний стан.", components: ["Портали для команди й клієнтів", "Панелі даних та адмінінструменти", "Калькулятори й кошториси", "API та CRM-інтеграції", "Календарі та платежі", "Синхронізація даних", "Невеликі застосунки й MVP"], fit: "Коли готове ПЗ майже підходить, таблиця тримає критичний процес або кілька програм вимагають копіювання даних.", scope: "Вузьку інтеграцію можна оцінити окремо. Великі системи часто перевищують $10,000 через серверну частину, права доступу чи перенесення даних.", impact: ["Менше ручної роботи", "Краща видимість"], workflow: ["Запит", "Спільні дані", "Правило", "Інструмент", "Видимий стан"] },
      { id: "diagnostic", title: "Діагностика / проєктування системи", statement: "Якщо проблема зрозуміла, а рішення — ні, визначте реалізацію до її замовлення.", problem: "Заявки губляться, процес забирає час або інструменти не пов’язані, але невідомо, чи потрібна сторінка, автоматизація, інтеграція або ПЗ.", build: "Вивчаємо вузьке місце, його важливість для бізнесу, поточні інструменти й найменшу реалізацію, що має сенс. Також визначаємо, що змінювати не слід.", after: "Ви отримуєте придатний до розробки обсяг, залежності, критерії приймання й план вимірювання — без нескінченних стратегічних документів.", components: ["Карта процесу й передач", "Комерційна важливість", "Огляд інструментів", "Запропонована дія", "Потрібні інтеграції", "Обсяг реалізації", "Вимірювання після запуску"], fit: "Коли ви знаєте, що втрачаєте гроші або час, але ще не можете визначити правильну систему й безпечний початок.", scope: "Сфокусована діагностика завершується конкретною рекомендацією. Подальшу реалізацію оцінюємо окремо за погодженими вимогами.", impact: ["Краща видимість", "Швидші операції"], workflow: ["Поточний процес", "Обмеження", "Варіанти", "Чіткий обсяг", "Вимірювання"] },
    ],
    examples: [
      { title: "Нова заявка", steps: ["Заявка", "Швидка відповідь", "Кваліфікація", "Запис", "CRM", "Сповіщення", "Супровід"], note: "Час і маршрутизацію визначають правила. ШІ може стисло описати нестандартний запит, якщо це корисно." },
      { title: "Пропущений дзвінок", steps: ["Дзвінок", "Автоматичне SMS", "Відповідь клієнта", "Категорія запиту", "Сповіщення команди"], note: "Тут здебільшого достатньо простого процесу без ШІ." },
      { title: "Запит із сайту", steps: ["Форма", "Витяг контексту", "Вибір команди", "Оновлення CRM", "Наступна дія"], note: "ШІ може зрозуміти вільний текст, а передача й нагадування працюють за чіткими правилами." },
      { title: "Запис на прийом", steps: ["Запис", "Підтвердження", "Нагадування", "Перевірка візиту", "Повідомлення після"], note: "Надійний процес із календарем і повідомленнями часто взагалі не потребує ШІ." },
    ],
  },
  de: {
    homeTitle: "Was das System tatsächlich verändert.",
    homeIntro: "Eine Seite, Automatisierung oder ein Tool zählt nur, wenn es eine konkrete Lücke im Ablauf schließt. Erkennen Sie Ihre Situation wieder?",
    flowTitle: "Eine Anfrage sollte nicht bis zum nächsten Arbeitstag warten.",
    flowIntro: "Diese Abläufe lassen sich mit Ihren bestehenden Werkzeugen aufbauen. Für manche Schritte reichen klare Regeln; KI ist nur sinnvoll, wenn Informationen interpretiert werden müssen.",
    flowLabel: "Ablauf wählen", flowNote: "Die genauen Schritte hängen von Ihren Tools, Einwilligungsregeln und der Arbeit Ihres Teams ab.",
    labels: { problem: "Wo es scheitert", build: "Was wir bauen", after: "Was sich ändert", components: "Typische Bausteine", fit: "Wann es passt", scope: "Möglicher Umfang", impact: "Geschäftlicher Effekt", workflow: "Beispielablauf", explore: "Umfang ansehen", discuss: "Diesen Engpass beschreiben" },
    heroTitle: "Wir bauen das fehlende System zwischen Aufmerksamkeit und Umsetzung.",
    heroLead: "Ausgangspunkt ist ein geschäftliches oder operatives Problem. Danach wählen wir die kleinste sinnvolle Kombination aus Oberfläche, Automatisierung, Integration und Software.",
    items: [
      { id: "conversion-systems", title: "Conversion-Systeme", statement: "Traffic ist teuer. Einen Kunden nach dem Klick zu verlieren, ist noch teurer.", problem: "Jemand kommt über eine Anzeige auf eine veraltete Seite, versteht das Angebot auf dem Handy nicht oder gibt bei einem langen Formular und unklarer Buchung auf.", build: "Wir verbinden Angebot, Vertrauen, Handlung und Übergabe, damit aus Interesse eine sinnvolle Anfrage oder Buchung werden kann.", after: "Der nächste Schritt ist klar, die Anfrage enthält Kontext und Tracking zeigt, wo Besucher den Weg verlassen.", components: ["Landingpages und Kampagnenseiten", "Kommerzielle Websites", "Angebot und CTA-Struktur", "Mobile Conversion-UX", "Formulare und Qualifizierung", "Buchung und CRM-Übergabe", "Analytik und Performance"], fit: "Wenn Sie bereits Traffic einkaufen, Anfragen ohne Kontext bekommen oder Kunden durch einen umständlichen Buchungsweg verlieren.", scope: "Ein fokussierter Landing-Sprint kann bei etwa $4,000 beginnen, eine größere Website bei etwa $8,500 liegen. Integrationen und Tiefe bestimmen den endgültigen Umfang.", impact: ["Mehr Umsatzchancen", "Bessere Übersicht"], workflow: ["Traffic", "Klares Angebot", "Vertrauen", "Handlung", "Qualifizierte Anfrage", "Übergabe"] },
      { id: "business-automation", title: "KI und Geschäftsautomatisierung", statement: "Eine Anfrage kommt um 22:14 Uhr. Antwort und Übergabe sollten nicht von der Inbox-Kontrolle am nächsten Morgen abhängen.", problem: "Interessenten warten, verpasste Anrufe gehen unter, Termine brauchen manuelle Erinnerungen und Daten werden zwischen E-Mail, Tabelle und CRM kopiert.", build: "Wir automatisieren wiederholte Arbeit rund um Ihr Team: Antwort, Routing, Nachverfolgung und Datenbewegung. KI nutzen wir, wenn Anfragen oder Dokumente wirklich interpretiert werden müssen.", after: "Die zuständige Person erhält früher den nötigen Kontext, Routine läuft verlässlich und Entscheidungen mit Ermessensspielraum bleiben beim Team.", components: ["Sofortige Antwort", "SMS nach verpasstem Anruf", "E-Mail- und SMS-Follow-up", "Qualifizierung und Routing", "Buchung und Erinnerungen", "CRM-Pipeline", "Dokumentenverarbeitung", "Interne Meldungen und Berichte"], fit: "Wenn Reaktionszeiten schwanken, der Vertrieb immer dieselben Schritte wiederholt oder Verwaltung die Leistungserbringung verzögert.", scope: "Ein einzelner Ablauf kann zuerst umgesetzt werden. Weitere Kanäle, Ausnahmen und Integrationen vergrößern den Umfang.", impact: ["Weniger Handarbeit", "Schnellere Abläufe"], workflow: ["Anfrage", "Sofortige Antwort", "Qualifizierung", "CRM-Update", "Zuständige Person", "Follow-up"] },
      { id: "custom-tools", title: "Individuelle Tools und Integrationen", statement: "Manchmal brauchen Sie kein weiteres Abo. Ihre vorhandene Software muss zusammenarbeiten.", problem: "Eine Tabelle ist zur internen Anwendung geworden. Mitarbeitende wiederholen Berechnungen, Systeme tauschen keine Daten aus und die Leitung hat keinen verlässlichen Überblick.", build: "Wir schaffen die fehlende Softwareschicht: ein fokussiertes Tool, Portal, Rechner, Dashboard oder eine Integration für den tatsächlichen Ablauf.", after: "Daten werden einmal erfasst, der Ablauf lässt sich leichter betreiben und Verantwortliche sehen den aktuellen Stand.", components: ["Team- und Kundenportale", "Dashboards und Admin-Tools", "Angebotsrechner", "API- und CRM-Integrationen", "Kalender und Zahlungen", "Datensynchronisierung", "Kleine Workflow-Apps und MVPs"], fit: "Wenn Standardsoftware fast passt, eine Tabelle einen wichtigen Prozess trägt oder mehrere Apps wiederholtes Kopieren verlangen.", scope: "Eine kleine Integration lässt sich separat abgrenzen. Größere Systeme liegen bei Backend, Rechten oder Datenmigration häufig über $10,000.", impact: ["Weniger Handarbeit", "Bessere Übersicht"], workflow: ["Anfrage", "Gemeinsame Daten", "Geschäftsregel", "Team-Tool", "Sichtbarer Status"] },
      { id: "diagnostic", title: "Diagnose / Systementwurf", statement: "Wenn das Problem bekannt ist, aber die Lösung nicht, definieren Sie die Umsetzung vor dem Kauf.", problem: "Anfragen verschwinden, ein Ablauf kostet Zeit oder Tools sind getrennt. Unklar ist, ob eine bessere Seite, Automatisierung, Integration oder Software hilft.", build: "Wir erfassen Engpass, geschäftliche Bedeutung, bestehende Tools und die kleinste sinnvolle Maßnahme. Wir benennen auch, was unverändert bleiben sollte.", after: "Sie erhalten einen umsetzbaren Umfang, Abhängigkeiten, Abnahmekriterien und einen Messplan statt eines endlosen Strategiedokuments.", components: ["Prozess- und Übergabekarte", "Geschäftliche Bedeutung", "Prüfung der Tools", "Vorgeschlagene Maßnahme", "Integrationsbedarf", "Umsetzungsumfang", "Messung nach Start"], fit: "Wenn Sie wissen, dass Geld oder Zeit verloren geht, aber das passende System und der sichere Einstieg noch unklar sind.", scope: "Eine fokussierte Diagnose endet mit einer konkreten Empfehlung. Eine folgende Umsetzung wird anhand vereinbarter Anforderungen separat bepreist.", impact: ["Bessere Übersicht", "Schnellere Abläufe"], workflow: ["Ist-Ablauf", "Engpass", "Optionen", "Umsetzbarer Umfang", "Messung"] },
    ],
    examples: [
      { title: "Neue Anfrage", steps: ["Anfrage", "Sofortige Antwort", "Qualifizierung", "Buchung", "CRM", "Benachrichtigung", "Follow-up"], note: "Regeln steuern Zeitpunkt und Routing. KI kann eine freie Anfrage bei Bedarf zusammenfassen." },
      { title: "Verpasster Anruf", steps: ["Anruf verpasst", "SMS gesendet", "Kunde antwortet", "Anliegen eingeordnet", "Team informiert"], note: "Ein einfacher, regelbasierter Ablauf reicht hier meist ohne KI aus." },
      { title: "Website-Anfrage", steps: ["Formular", "Kontext erfasst", "Team zugeordnet", "CRM aktualisiert", "Nächster Schritt"], note: "KI kann Freitext verstehen; Routing und Follow-up bleiben eindeutige Regeln." },
      { title: "Termin", steps: ["Buchung", "Bestätigung", "Erinnerung", "Teilnahmeprüfung", "Nachricht danach"], note: "Ein verlässlicher Kalender- und Nachrichtenablauf benötigt oft gar keine KI." },
    ],
  },
};
